### PR TITLE
readme: fix erroneous service instantiation

### PR DESCRIPTION
**Pull request by mkozjak**
jsonws.api('1.0.0', 'test api') throws 'TypeError: jsonws.api is not a function'

### CODE REVIEW

**Comment by mkozjak** [comment]
```jsonws.api``` works only from git master.

**Comment by mihail-stanchev** [comment]
Hey, thanks for your feedback. We are working on a couple of issues in the dev/2.0 branch and plan to merge this in master soon. The 2.0 API has been improved so creating a service is now done e.g.
`var serviceInstance = new jsonws.service('1.0.0', 'Test API')`

**Comment by mkozjak** [comment]
Hi, @mihail-stanchev! Thanks for the feedback!

Also, ```api.transport``` from the docs doesn't work, either, but you already know it already.
How do you recommend me to use this library? Should I use the dev/2.0 branch? Are the docs there up-to-date?

**Comment by mihail-stanchev** [comment]
The best way is to check out test/adhoc/app.js in the dev/2.0 branch. The docs are not completely up-to-date as this is still WIP. I'd be happy to answer any of your questions, though :)
Setting up a project is quite simple:
1. Have your HTTP server ready
2. Create a registry - an endpoint which will intercept all calls to a particular root path
3. Attach transports (HTTP and/or WebSocket currently) to your registry
4. Attach services to your registry
All of this is demonstrated in the test\adhoc app.

**Comment by mkozjak** [comment]
Thank you for the explanation. This library looks promising, btw. Good work!
